apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-despachos
  namespace: tienda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-despachos
  template:
    metadata:
      labels:
        app: api-despachos
    spec:
      containers:
      - name: api-despachos
        image: 053777337110.dkr.ecr.us-east-1.amazonaws.com/innovatech-despachos
        ports:
        - containerPort: 8080
        env:
          # Forzamos la URL directa de Spring Boot
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:mysql://mysql.tienda.svc.cluster.local:3306/tienda_perritos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
          - name: SPRING_DATASOURCE_USERNAME
            value: "root"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "mysql"
          # Agregamos las variables que tu log dice que faltan por si acaso
          - name: DB_ENDPOINT
            value: "mysql.tienda.svc.cluster.local"
          - name: DB_PORT
            value: "3306"
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-despachos
  namespace: tienda
spec:
  selector:
    app: api-despachos
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-despachos
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-despachos
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50