apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-ventas
  namespace: tienda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-ventas
  template:
    metadata:
      labels:
        app: api-ventas
    spec:
      containers:
      - name: api-ventas
        image: 842973764258.dkr.ecr.us-east-1.amazonaws.com/innovatech-ventas:latest
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:mysql://tienda-db.tienda.svc.cluster.local:3306/tienda_perritos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
          - name: SPRING_DATASOURCE_USERNAME
            value: "root"
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-ventas
  namespace: tienda
spec:
  selector:
    app: api-ventas
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-ventas
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-ventas
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
