apiVersion: apps/v1
kind: Deployment
metadata:
  name: Frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Frontend
  template:
    metadata:
      labels:
        app: Frontend
    spec:
      containers:
      - name: Frontend
        image: 053777337110.dkr.ecr.us-east-1.amazonaws.com/innovatech-frontend
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-Frontend
spec:
  selector:
    app: Frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-Frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: Frontend
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50